version: "3.9"
services:
  backend:
    build: .
    networks:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  db:
    image: postgres:14
    networks:
      - db
    ports:
      - "5432"
    environment:
      POSTGRES_DB: gc
      POSTGRES_PASSWORD: gc
    volumes:
      - data:/var/lib/postgresql/data
networks:
  db:
volumes:
  data: