spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gc
    username: postgres
    initialization-mode: always


logging:
  level:
    org.springframework:
      web:
        client:
          RestTemplate: DEBUG

groundspeak:
  consumer_key: ...
  username: ...
  password: ...